name: Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generar release notes
        run: echo "Release generado automáticamente por Altiora-Tech"
      - name: Publicar
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true